name: myenv
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=pyhd8ed1ab_1
  - blas=1.0=openblas
  - bottleneck=1.4.2=py39ha9d4c09_0
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.10.5=hbd8a1cb_0
  - comm=0.2.3=pyhe01879c_0
  - debugpy=1.8.16=py39hbdd6827_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.0=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.2=pyhd8ed1ab_1
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libopenblas=0.3.30=h46f56fc_0
  - libsodium=1.0.20=heac8642_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - numexpr=2.10.1=py39hd28fd6d_0
  - numpy=2.0.2=py39hc213724_2
  - numpy-base=2.0.2=py39hf387b04_2
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.3=py39h505adc9_0
  - parso=0.8.4=pyhd8ed1ab_1
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - platformdirs=4.3.8=pyhe01879c_0
  - prompt-toolkit=3.0.51=pyha770c72_0
  - psutil=5.9.1=py39hb9d737c_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-tzdata=2025.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytz=2025.2=py39h06a4308_0
  - pyzmq=27.1.0=py39hcf8288c_0
  - readline=8.3=hc2a1206_0
  - six=1.17.0=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - tk=8.6.15=h54e0aa7_0
  - traitlets=5.14.3=pyhd8ed1ab_1
  - typing_extensions=4.14.1=pyhe01879c_0
  - tzdata=2025b=h04d1e81_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zeromq=4.3.5=hb0a5e54_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - altair==5.5.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.0
      - certifi==2025.10.5
      - charset-normalizer==3.4.3
      - click==8.1.8
      - fastjsonschema==2.21.2
      - gitdb==4.0.12
      - gitpython==3.1.45
      - idna==3.10
      - jinja2==3.1.6
      - jsonschema==4.25.1
      - jsonschema-specifications==2025.9.1
      - markupsafe==3.0.3
      - narwhals==2.7.0
      - nbformat==5.10.4
      - pillow==11.3.0
      - pip==25.3
      - plotly==6.4.0
      - protobuf==6.32.1
      - pyarrow==21.0.0
      - pydeck==0.9.1
      - pyyaml==6.0.3
      - referencing==0.36.2
      - requests==2.32.5
      - rpds-py==0.27.1
      - setuptools==80.9.0
      - smmap==5.0.2
      - streamlit==1.50.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.2
      - typing-extensions==4.15.0
      - urllib3==2.5.0
      - watchdog==6.0.0
prefix: /home/ravi/miniconda3/envs/myenv
